config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             class_name: 'User',
             module: :devise,
             controllers: { sessions: 'users/sessions',
                            passwords: 'users/passwords' },
             skip: [:unlocks, :omniauth_callbacks, :registrations],
             path_names: { sign_out: 'logout' }

  devise_scope :user do
    get 'authorization_failure', to: 'users/sessions#authorization_failure', as: :unauthorized
    get 'login' => 'users/sessions#new', :as => :login
    post 'login' => 'users/sessions#create', :as => :create_new_session
    get 'logout' => 'users/sessions#destroy', :as => :logout
  end

  get 'dashboard' => 'dashboard#index', as: 'dashboard'

  namespace :user do
    root :to => 'dashboard#index'
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'index' => 'home#index', as: 'index'
  root 'home#index'

  resources :experiences,    only:   [:index]

  resources :jobs,           except: [:show, :index]
  resources :certifications, except: [:show, :index]
  resources :degrees,        except: [:show, :index]
  resources :volunteers,     except: [:show, :index]

  resources :projects,       only:   [:index]

  resources :samples,        except: [:show, :index]
  resources :engines,        except: [:show, :index]
  resources :games,          except: [:show, :index]
  resources :mobile_apps,    except: [:show, :index]

  resources :technologies,   except: [:show]
  resources :tags,           except: [:show]
  resources :contents,       except: [:show]
end

app/models/project.rb
class Project < ApplicationRecord
	scope :samples,     -> { where(group: :sample) }
	scope :engines,     -> { where(group: :engine) }
	scope :games,       -> { where(group: :game) }
	scope :mobile_apps, -> { where(group: :mobile_app) }

	has_many :project_tags
  has_many :tags, through: :project_tags

	has_rich_text :description
  has_rich_text :notice
  has_rich_text :issues
  has_rich_text :content_source

	with_options presence: true do
		validates :group
		validates :title
  end

  def save_tags(y)
    x = self.tags.present? ? self.tags.pluck(:id) : []
    # Validate presence of array y and convert its elements to integers.
    y = y.nil? ? [] : y.map { |s| s.to_i }
    # (x - y) is getting the elements in array x that are not in array y. These elements are to be destroyed.
    # (y - x) is getting the elements in array y that are not in array x. These elements are to be created if not exist see.
    begin
      ProjectTag.where(project: self, tag_id: (x-y)).destroy_all
      ((y - x) - self.tags.pluck(:id)).uniq.each do |b_id|
        ProjectTag.create!(project: self, tag: Tag.find(b_id))
      end
    rescue
      @not_valid_tags = true
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < AdminController
  def index
  end
  
	def new
    @project = project_model.new
  end

  def create
    @project = project_model.new(project_params)  
    if @project.save
      respond_to do |format|
        flash[:success] = I18n.t(:success, resource_name: project_model.model_name.human, scope: [:flash, :actions, :create])
	      format.html { redirect_to projects_url }
	    end
    else
      render 'new'
    end
  end

  def edit
    @project = project_model.find(params[:id])
  end

  def update
    @project = project_model.find(params[:id])
    @project.assign_attributes(project_params)
    if project_save
	    respond_to do |format|
        flash[:success] = I18n.t(:success, resource_name: project_model.model_name.human, scope: [:flash, :actions, :update])
	      format.html { redirect_to projects_url }
	    end
	  else
      render 'edit'
    end
  end

  def destroy
    project = project_model.find(params[:id])
    project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.js   { render :layout => false }
    end
  end

  private

  def project_model
     @project_model = controller_name.classify.constantize
  end

  def project_params
    params.require(project_model.name.underscore.to_sym).permit(:title, :link, :notice, :issues, :description, :content_source, :release_date, :currently_working_on)
  end

  def project_save
    Project.transaction do
      @project.save_tags(params[project_model.name.underscore.to_sym][:tags])
      @project.save
    end
  end
end

app/views/projects/_form.html.erb
<div class="row">
  <div class="input-field col s12 m6">
    <%= form.label :title, :class => 'active'  %><br>
    <%= form.text_field :title %>
  </div>

  <div class="input-field col m6 s12">
    <%= form.label :link, :class => 'active'  %><br>
    <%= form.text_field :link %>
  </div>

  <div class="input-field col s12">
    <%= form.text_field :release_date, :class => 'datepicker' %>
    <%= form.label :release_date, :class => 'active' %>
  </div>

  <div class="input-field col s12">
    <%= form.label :tags, :class => 'active' %><br>
    <% tags = Tag.all %>
    <% selected_tags = form.object.tags.any? ? form.object.tags : [] %>
    <%= select_tag "#{form.object.model_name.name.parameterize}[tags][]", options_from_collection_for_select(tags, 'id', 'name', selected_tags.pluck(:id)), { :multiple => true } %>
  </div>

  <div class="input-field col s12">
    <%= form.label :description %><br><br>
    <%= form.rich_text_area :description %>
  </div>

  <div class="input-field col s12">
    <%= form.label :content_source %><br><br>
    <%= form.rich_text_area :content_source %>
  </div>

  <div class="input-field col s12">
    <%= form.label :notice %><br><br>
    <%= form.rich_text_area :notice %>
  </div>
  
  <div class="input-field col s12">
    <%= form.label :issues %><br><br>
    <%= form.rich_text_area :issues %>
  </div>

  <div class="col s12 m6">
    <label>
      <%= form.check_box :currently_working_on, :class => 'filled-in' %>
      <span><%= I18n.t(:currently_working_on, scope: [:activerecord, :attributes]) %></span>
    </label><br><br>
  </div>
</div>

<script type="text/javascript">
  document.addEventListener("turbolinks:load", function() {
    $('select').formSelect();
    $('.datepicker').datepicker();
  })
</script>

app/views/projects/_grid.html.erb
<table style="table-layout: fixed">
  <colgroup>
    <col style="width:  5%" />
    <col style="width: 30%" />
    <!-- <col style="width: 15%" />*/ -->
    <col style="width: 30%" />
    <col style="width:  5%" />
    <col style="width: 30%" />
  </colgroup>

  <thead>
    <tr>
      <th></th>
      <th><%= I18n.t(:title, scope: [:activerecord, :attributes]) %></th>
      <!-- <th><%#= I18n.t(:release_date, scope: [:activerecord, :attributes]) %></th> -->
      <th><%= I18n.t(:tag, scope: [:activerecord, :models]).pluralize %></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% project_model.order(release_date: :desc).each do |p| %>
      <tr>
        <td><%= project_icon_tag p.group %></td>
        <td><%= p.title %></td>
        <!-- <td><%#= p.release_date %></td> -->
        <td><%= p.tags.map { |t| content_tag :div, h(t.name), class: "chip" }.join.html_safe unless p.tags.empty? %></td>
        <td><% if p.link.present? %><a href="<%= p.link %>"><i class="fa fa-link"></i><% end %></td>
        <td class="right">
          <%= link_to_edit p, :class => "waves-effect waves-black btn-flat black-text edit-trigger" do %>
            <%= material_icon_tag :create, nil, :class => 'black-text' %>
          <% end %>
          <%= link_to_destroy p, :class => "waves-effect waves-black btn-flat black-text delete-trigger" do %>
            <%= material_icon_tag :delete, nil, :class => 'black-text' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br><br>

app/views/projects/_wrapper.html.erb
<div class="content-block">
  <div id="experiences" class="row">
    <div class="col s12">
      <h5><%= I18n.t(:project, scope: [:activerecord, :models]).pluralize %></h5>
      <% [Sample, Engine, Game, MobileApp].each do |m| %>
        <%= render partial: 'projects/grid', locals: { project_model: m } %>
      <% end %>

      <div class="actions">
        <div class="fixed-action-btn">
          <a class="btn-floating btn-large">
            <i class="large material-icons">mode_edit</i>
          </a>
          <ul>
            <li><%= link_to new_mobile_app_path, :class => "btn btn-floating" do %><i class="fa fa-mobile"></i><% end %></li>
            <li><%= link_to new_game_path, :class => "btn btn-floating" do %><i class="fa fa-chess"></i><% end %>
            </li>
            <li><%= link_to new_engine_path, :class => "btn btn-floating" do %><i class="fa fa-cube"></i><% end %></li>
            <li><%= link_to new_sample_path, :class => "btn btn-floating" do %><i class="fa fa-flask"></i><% end %></li>
          </ul>

        </div>
      </div>

    </div>
  </div>

</div>

<script type="text/javascript">
  document.addEventListener("turbolinks:load", function() {
    var elems = document.querySelectorAll('.fixed-action-btn');
    var instances = M.FloatingActionButton.init(elems, {
      direction: 'left',
      hoverEnabled: false
    });
  });
</script>

app/views/projects/edit.html.erb
<%= render partial: 'shared/error_messages', locals: { target: @project } %>

<%= form_for @project do |form| %>
  <h5><%= @project_model.header %></h5>
  <%= render partial: 'form', locals: { form: form } %>

  <%= render 'shared/submit', form: form %>
<% end %>

app/views/projects/index.html.erb
<section class="col s12">
  <h4><span class="main-title"><%= I18n.t(:project, scope: [:activerecord, :models]).pluralize %></span></h4>
  <%= render partial: 'shared/error_messages', locals: { target: nil } %>
  <%= render partial: 'wrapper' %>
</section>

app/views/projects/new.html.erb
<%= render partial: 'shared/error_messages', locals: { target: @project } %>

<%= form_for @project do |form| %>
  <h5><%= @project_model.header %></h5>
  <%= render partial: 'form', locals: { form: form } %>

  <%= render 'shared/submit', form: form %>
<% end %>