config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             class_name: 'User',
             module: :devise,
             controllers: { sessions: 'users/sessions',
                            passwords: 'users/passwords' },
             skip: [:unlocks, :omniauth_callbacks, :registrations],
             path_names: { sign_out: 'logout' }

  devise_scope :user do
    get 'authorization_failure', to: 'users/sessions#authorization_failure', as: :unauthorized
    get 'login' => 'users/sessions#new', :as => :login
    post 'login' => 'users/sessions#create', :as => :create_new_session
    get 'logout' => 'users/sessions#destroy', :as => :logout
  end

  get 'dashboard' => 'dashboard#index', as: 'dashboard'

  namespace :user do
    root :to => 'dashboard#index'
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'index' => 'home#index', as: 'index'
  root 'home#index'

  resources :experiences,    only:   [:index]

  resources :jobs,           except: [:show, :index]
  resources :certifications, except: [:show, :index]
  resources :degrees,        except: [:show, :index]
  resources :volunteers,     except: [:show, :index]

  resources :projects,       only:   [:index]

  resources :samples,        except: [:show, :index]
  resources :engines,        except: [:show, :index]
  resources :games,          except: [:show, :index]
  resources :mobile_apps,    except: [:show, :index]

  resources :technologies,   except: [:show]
  resources :tags,           except: [:show]
  resources :contents,       except: [:show]
end

app/models/experience.rb
class Experience < ApplicationRecord
	scope :jobs, -> { where(group: :job) }
	scope :degrees, -> { where(group: :degree) }
	scope :certifications, -> { where(group: :certification) }
	scope :volunteers, -> { where(group: :volunteer) }

	has_rich_text :description

	with_options presence: true do
		validates :group
		validates :title
	  validates :description
    validates :start_date
  end

  validate :time_range

  def self.groups
  	return [I18n.t(:job, scope: [:views, :resume, :experiences]),
            I18n.t(:degree, scope: [:views, :resume, :experiences]),
            I18n.t(:certification, scope: [:views, :resume, :experiences]),
            I18n.t(:volunteer, scope: [:views, :resume, :experiences])]
  end

  private

  def time_range
    if self.start_date.present? && self.end_date.present?
      errors.add(:start_date, I18n.t(:invalid_time, scope: [:errors, :messages])) if self.start_date > self.end_date
    end
  end
end

app/controllers/experiences_controller.rb
class ExperiencesController < AdminController
  def index    
  end

	def new
    @experience = experience_model.new
  end

  def create
    @experience = experience_model.new(experience_params)  
    if @experience.save
      respond_to do |format|
        flash[:success] = I18n.t(:success, resource_name: experience_model.model_name.human, scope: [:flash, :actions, :create])
	      format.html { redirect_to experiences_url }
	    end
    else
      render 'new'
    end
  end

  def edit
    @experience = experience_model.find(params[:id])
  end

  def update
    @experience = experience_model.find(params[:id])
    if @experience.update(experience_params)
	    respond_to do |format|
        flash[:success] = I18n.t(:success, resource_name: experience_model.model_name.human, scope: [:flash, :actions, :update])
	      format.html { redirect_to experiences_url }
	    end
	  else
      render 'edit'
    end
  end

  def destroy
    experience = experience_model.find(params[:id])
    experience.destroy
    respond_to do |format|
      format.html { redirect_to experiences_url }
      format.js   { render :layout => false }
    end
  end

  private

  def experience_model
     @experience_model = controller_name.classify.constantize
  end

  def experience_params
    params.require(experience_model.name.underscore.to_sym).permit(:title, :organization, :location, :start_date, :end_date, :description, :credentials, :currently_working_on)
  end
end

app/views/experiences/_form.html.erb
<div class="row">
  <div class="input-field col s12">
    <%= form.label :title, :class => 'active'  %><br>
    <%= form.text_field :title %>
  </div>

  <!-- <div class="input-field col s12 m6">
    <%#= form.label :group, :class => 'active' %><br>
    <%#= form.select(:group, options_for_select(Experience.groups), { include_blank: false }) %>
  </div> -->

  <div class="input-field col s12 m6">
    <%= form.label :organization, :class => 'active'  %><br>
    <%= form.text_field :organization %>
  </div>

  <div class="input-field col s12 m6">
    <%= form.label :location, :class => 'active'  %><br>
    <%= form.text_field :location %>
  </div>

  <div class="input-field col s12 m6">
    <%= form.text_field :start_date, :class => 'datepicker' %>
    <%= form.label :start_date, :class => 'active' %>
  </div>

  <div class="input-field col s12 m6">
    <%= form.text_field :end_date, :class => 'datepicker' %>
    <%= form.label :end_date, :class => 'active' %>
  </div>

  <div class="input-field col s12">
    <%= form.label :description %><br><br>
    <%= form.rich_text_area :description %>
  </div>
  
  <% if @experience_model == Certification %>
    <div class="input-field col s12">
      <%= form.label :credentials %><br><br>
      <%= form.rich_text_area :credentials %>
    </div>
  <% end %>

  <div class="col s12 m6">
    <label>
      <%= form.check_box :currently_working_on, :class => 'filled-in' %>
      <span><%= I18n.t(:currently_working_on, scope: [:activerecord, :attributes]) %></span>
    </label><br><br>
  </div>
</div>

<script type="text/javascript">
  document.addEventListener("turbolinks:load", function() {
    $('select').formSelect();
    $('.datepicker').datepicker();
  })
</script>

app/views/experiences/_grid.html.erb
<table style="table-layout: fixed">
  <colgroup>
    <col style="width:  5%" />
    <col style="width: 35%" />
    <col style="width: 10%" />
    <col style="width: 10%" />
    <col style="width: 30%" />
  </colgroup>

  <thead>
    <tr>
      <th></th>
      <th><%= I18n.t(:title, scope: [:activerecord, :attributes]) %></th>
      <th><%= I18n.t(:start_date, scope: [:activerecord, :attributes]) %></th>
      <th><%= I18n.t(:end_date, scope: [:activerecord, :attributes]) %></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% experience_model.order(start_date: :desc).each do |e| %>
      <tr>
        <td><%= experience_icon_tag e.group %></td>
        <td><%= e.title %></td>
        <td><%= e.start_date %></td>
        <td><%= e.end_date %></td>
        <td class="right">
          <%= link_to_edit e, :class => "waves-effect waves-black btn-flat black-text edit-trigger" do %>
            <%= material_icon_tag :create, nil, :class => 'black-text' %>
          <% end %>
          <%= link_to_destroy e, :class => "waves-effect waves-black btn-flat black-text delete-trigger" do %>
            <%= material_icon_tag :delete, nil, :class => 'black-text' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br><br>

app/views/experiences/_wrapper.html.erb
<div class="content-block">
  <div id="experiences" class="row">
    <div class="col s12">
      <h5><%= I18n.t(:experience, scope: [:activerecord, :models]).pluralize %></h5>
      <% [Job, Certification, Degree, Volunteer].each do |m| %>
        <%= render partial: 'experiences/grid', locals: { experience_model: m } %>
      <% end %>

      <div class="actions">
        <div class="fixed-action-btn">
          <a class="btn-floating btn-large">
            <i class="large material-icons">mode_edit</i>
          </a>
          <ul>
            <li><%= link_to new_volunteer_path, :class => "btn btn-floating" do %><i class="fa fa-hand-holding-heart"></i><% end %></li>
            <li><%= link_to new_certification_path, :class => "btn btn-floating" do %><i class="fa fa-certificate"></i><% end %>
            </li>
            <li><%= link_to new_degree_path, :class => "btn btn-floating" do %><i class="fa fa-scroll"></i><% end %></li>
            <li><%= link_to new_job_path, :class => "btn btn-floating" do %><i class="fa fa-briefcase"></i><% end %></li>
          </ul>

        </div>
      </div>

    </div>
  </div>

</div>

<script type="text/javascript">
  document.addEventListener("turbolinks:load", function() {
    var elems = document.querySelectorAll('.fixed-action-btn');
    var instances = M.FloatingActionButton.init(elems, {
      direction: 'left',
      hoverEnabled: false
    });
  });
</script>

app/views/experiences/edit.html.erb
<%= render partial: 'shared/error_messages', locals: { target: @experience } %>

<%= form_for @experience do |form| %>
  <h5><%= @experience_model.header %></h5>
  <%= render partial: 'form', locals: { form: form } %>

  <%= render 'shared/submit', form: form %>
<% end %>

app/views/experiences/index.html.erb
<section class="col s12">
  <h4><span class="main-title"><%= I18n.t(:experience, scope: [:activerecord, :models]).pluralize %></span></h4>
  <%= render partial: 'shared/error_messages', locals: { target: nil } %>
  <%= render partial: 'wrapper' %>
</section>

app/views/experiences/new.html.erb
<%= render partial: 'shared/error_messages', locals: { target: @experience } %>

<%= form_for @experience do |form| %>
  <h5><%= @experience_model.header %></h5>
  <%= render partial: 'form', locals: { form: form } %>

  <%= render 'shared/submit', form: form %>
<% end %>