config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             class_name: 'User',
             module: :devise,
             controllers: { sessions: 'users/sessions',
                            passwords: 'users/passwords' },
             skip: [:unlocks, :omniauth_callbacks, :registrations],
             path_names: { sign_out: 'logout' }

  devise_scope :user do
    get 'authorization_failure', to: 'users/sessions#authorization_failure', as: :unauthorized
    get 'login' => 'users/sessions#new', :as => :login
    post 'login' => 'users/sessions#create', :as => :create_new_session
    get 'logout' => 'users/sessions#destroy', :as => :logout
  end

  get 'dashboard' => 'dashboard#index', as: 'dashboard'

  namespace :user do
    root :to => 'dashboard#index'
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'index' => 'home#index', as: 'index'
  root 'home#index'

  resources :experiences,    only:   [:index]

  resources :jobs,           except: [:show, :index]
  resources :certifications, except: [:show, :index]
  resources :degrees,        except: [:show, :index]
  resources :volunteers,     except: [:show, :index]

  resources :projects,       only:   [:index]

  resources :samples,        except: [:show, :index]
  resources :engines,        except: [:show, :index]
  resources :games,          except: [:show, :index]
  resources :mobile_apps,    except: [:show, :index]

  resources :technologies,   except: [:show]
  resources :tags,           except: [:show]
  resources :contents,       except: [:show]
end

app/models/tag.rb
class Tag < ApplicationRecord
	validates :name, presence: true, uniqueness: { case_sensitive: false }

  def self.save_multiple(names)
    saved_tags = [];
    names.split(",").reject(&:blank?).each do |name|
      tag = Tag.new({name: name})
      if tag.save
        saved_tags << tag
      end unless Tag.find_by_name(name)
    end
    return saved_tags
  end

  def <=> (other)
    name <=> other.name
  end

  def to_s
    name
  end
end

app/controllers/tags_controller.rb
class TagsController < AdminController
  def index
    @tags = Tag.order(name: :asc)
  end

	def create
    if params.has_key?(:names) 
      saved_tags = Tag.save_multiple(params[:names])

      resource_name = saved_tags.count > 1 ? Tag.model_name.human.pluralize : Tag.model_name.human.singularize
      if saved_tags.any?
        flash[:success] = I18n.t(:success, resource_name: resource_name, scope: [:flash, :actions, :create])
      else 
        flash[:failure] = I18n.t(:failure, resource_name: resource_name, scope: [:flash, :actions, :create])
      end
      redirect_to tags_path
    end
	end

  def destroy
    tag = Tag.find(params[:id])

    tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_path }
      format.js   { render :layout => false }
    end      
  end
end

app/views/tags/_grid.html.erb
<div class="content-block">
  <div id="tags" class="row">
    <div class="col s12">
      <h5><%= I18n.t(:tag, scope: [:activerecord, :models]).pluralize %></h5>

      <% @tags.each do |tag| %>
        <div class="chip">
          <%= tag.name %>
          <%= link_to tag_path(id: tag.id), method: :delete do %>
              <i class="close material-icons">close</i>
            <% end %>
        </div>
      <% end unless @tags.nil? %>
    </div>
  </div>  
  <div class="actions">
    <div class="action-btn">
      <a class="waves-effect waves-light btn-floating btn-large modal-trigger" href="#new_tag_modal">
        <%= material_icon_tag :add, nil, :class => 'large' %>
      </a>
    </div>
  </div>                  
</div>

<div id="new_tag_modal" class="modal">
  <%= form_tag :tags, method: :post do %>
    <div class="modal-content left-align">
      <h5 class="border-b-1 p-b-10"><%= I18n.t(:create_multiple, resource: Tag.model_name.human.pluralize, scope: [:views, :actions])%></h5>
        <div class="chips"></div>
        <%= hidden_field_tag :names, nil, id: 'tag_names' %>
    </div>
    <div class="modal-footer">
      <%= render "shared/submit_modal" %>
    </div>
  <% end %>
</div>

<script type="text/javascript">
  document.addEventListener("turbolinks:load", function() {
    $('.modal').modal();
    $('.chips').chips({
      placeholder: 'Enter a tag',
      secondaryPlaceholder: '+Tag',
      autocompleteOptions: {
        data: {
          'Ruby': null,
          'Ruby on Rails': null,
          'JavaScript': null,
          'Node': null,
          'Express': null,
          'React': null,
          'React Native': null,
          'Python': null,
          'Linux': null,
          'MySQL': null,
          'MariaDB': null,
          'PostgreSQL': null,
          'MongoDB': null,
          'HTML': null,
          'SASS': null,
          'LESS': null,
          'CSS': null
        },
        limit: Infinity,
        minLength: 1
      },
      onChipAdd: function(chip){
        let tag = this.chipsData[this.chipsData.length - 1].tag + ', ';
        $('#tag_names').val($('#tag_names').val() + `${tag}`);
      }
    });
  })

  $(document).on('click', '.modal-trigger', function (e) {
    e.preventDefault();
    let elem = document.querySelector('.modal');
    let instance = M.Modal.getInstance(elem);
    instance.open();
  })
</script>

app/views/tags/index.html.erb
<section class="col s12">
  <h4><span class="main-title"><%= I18n.t(:tag, scope: [:activerecord, :models]).pluralize %></span></h4>
  <%= render partial: 'shared/error_messages', locals: { target: nil } %>
  <%= render partial: 'grid' %>
</section>