config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             class_name: 'User',
             module: :devise,
             controllers: { sessions: 'users/sessions',
                            passwords: 'users/passwords' },
             skip: [:unlocks, :omniauth_callbacks, :registrations],
             path_names: { sign_out: 'logout' }

  devise_scope :user do
    get 'authorization_failure', to: 'users/sessions#authorization_failure', as: :unauthorized
    get 'login' => 'users/sessions#new', :as => :login
    post 'login' => 'users/sessions#create', :as => :create_new_session
    get 'logout' => 'users/sessions#destroy', :as => :logout
  end

  get 'dashboard' => 'dashboard#index', as: 'dashboard'

  namespace :user do
    root :to => 'dashboard#index'
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'index' => 'home#index', as: 'index'
  root 'home#index'

  resources :experiences,    only:   [:index]

  resources :jobs,           except: [:show, :index]
  resources :certifications, except: [:show, :index]
  resources :degrees,        except: [:show, :index]
  resources :volunteers,     except: [:show, :index]

  resources :projects,       only:   [:index]

  resources :samples,        except: [:show, :index]
  resources :engines,        except: [:show, :index]
  resources :games,          except: [:show, :index]
  resources :mobile_apps,    except: [:show, :index]

  resources :technologies,   except: [:show]
  resources :tags,           except: [:show]
  resources :contents,       except: [:show]
end

app/views/layouts/admin_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nickthegeek</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'admin_application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <nav class="nav-extended">
      <div class="nav-wrapper">
        <a href="#" data-target="navbar" class="sidenav-trigger" style="display: block"><i class="material-icons">menu</i></a>
        <ul>
          <li class="right"><%= link_to dashboard_path do %><i class="fa fa-home"></i><% end %></li>
        </ul>
      </div>
    </nav>

    <ul class="sidenav " id="navbar">
      <li><%= link_to experiences_path do %><i class="fa fa-certificate"></i><%= I18n.t(:experience, scope: [:activerecord, :models]).pluralize %><% end %></li>
      <li><%= link_to technologies_path do %><i class="fa fa-gem"></i><%= I18n.t(:technology, scope: [:activerecord, :models]).pluralize %><% end %></li>
      <li><%= link_to tags_path do %><i class="fa fa-tag"></i><%= I18n.t(:tag, scope: [:activerecord, :models]).pluralize %><% end %></li>
      <li><%= link_to contents_path do %><i class="fa fa-align-left"></i><%= I18n.t(:content, scope: [:activerecord, :models]).pluralize %><% end %></li>
      <li><%= link_to projects_path do %><i class="fa fa-project-diagram"></i><%= I18n.t(:project, scope: [:activerecord, :models]).pluralize %><% end %></li>
      <li>
        <% if user_signed_in? %>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out-alt"></i>     
            <%= I18n.t(:account_sign_out, scope: [:devise, :views]) %>
          <% end %>
        <% end %> 
      </li>
    </ul>

    <main class="container">
      <div class="row">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

<script type="text/javascript">
  document.addEventListener("turbolinks:load", function() {
    $("#success_message").delay(3000).slideUp(300);
    $("#error_message").delay(3000).slideUp(300);
    
    $('.sidenav').sidenav();
    $(document).on('click', '.sidenav-trigger', function (e) {
      e.preventDefault();
      let elem = document.querySelector('.sidenav');
      let instance = M.Sidenav.getInstance(elem);
      instance.open();
    })

  })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nickthegeek</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  </head>

  <body>
    <%#= render partial: "shared/preloader" %>
    <%= render partial: "shared/navbar" %>
    <%= yield %>
    <%= render partial: "shared/footer" %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nickthegeek</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <div class="container valign-wrapper" style="height: 100vh">
      <div class="row">
        <%= yield %>
    </div>
  </body>
</html>